FROM ubuntu:22.04

RUN export DEBIAN_FRONTEND=noninteractive \
	&& ln -fs /usr/share/zoneinfo/UTC /etc/localtime

RUN apt-get update && apt-get install -y tzdata build-essential cmake
RUN dpkg-reconfigure --frontend noninteractive tzdata
RUN apt-get install -y libmysqlclient-dev libsqlite3-dev libboost-all-dev libgmp3-dev \
	liblua5.1-dev libxml2-dev
# mysql-server

RUN apt-get clean && apt-get autoclean

ENV PATH="/otserver:${PATH}"
VOLUME /otserver
